language: node_js
deploy:
  provider: heroku
  api_key:
    secure: QXZhiZgDWnqqucXmDo3X7dSSw9eUVcXDSdpDMpkgmsHqrdXIIRqm2m1lIMV6/MnnXOAi9sEMc+OMaabxdb8dyf6GVj9VXqY6/7h2hZ8bNHyUR/vCnQsyATJTeG3gKViePAZN1i0I2y1BkLDOHeiKsU4ECTxbHMklIaBbxJyO04J9Z4PND6gJ2fUn2QKX+tTrIXs5rQRKRwh11LqQU4vXaV7GQvyyyrbz721XV3nA5D2gPSjQyTY2eb6C0wZsUrbDoiPcN5fUqAJKJPbHPKszqYh4GZTYCy16+Qz6VfJtLlw+9BikbuC1ZObtS/6ZKz1wqI3pA1xqJZwSp6/bGnTliMrcuVwrD+PXM+4inpwFRHqIGDoHLG6UfVK4CagMlWDOK3UYFGk5DSytnAmBBVMloS3OdKYumXzri1ItaOztEvfomNSWgiH5mJ56zTFQUotGOeHeWcj9XtRp3VJmtEhWHWGjd1yRiOt6GKoddYKu8sA/U8/usgiOWodcjlQpyerLj5akztn0ttRJHt/bFlS8E+WFAqAfJlv4XnzOJXh3wfyLx54zaX+gBfLN1IiVjCfdxhPmgApMkeVAksgpTkA53hcTGsjCoBZSrZ9YLOHcpFiog6PJ1HgjmMCtngJPDlmXSga7KdpkkucPjGrK4w9KQjme7pVaAHzBWQ9f8fM+XGk=
  app: emaily-server
  